import type { Config } from "tailwindcss";

export default {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-background": "#2e1a28",
        "primary-container": "#f080c0",
        "primary-fixed-dim": "#f0a0cc",
        "tertiary-fixed": "#c8eaff",
        "outline-variant": "#dcc8e0",
        "background": "#fef7ff",
        "tertiary": "#0096cc",
        "inverse-primary": "#f0a0cc",
        "secondary": "#7c52aa",
        "tertiary-container": "#40c0ee",
        "on-secondary-fixed-variant": "#4a3068",
        "on-primary": "#ffffff",
        "surface-container-high": "#f2e8f2",
        "on-secondary-fixed": "#1a1030",
        "secondary-fixed-dim": "#c8a8e8",
        "on-tertiary-container": "#00334d",
        "on-error": "#ffffff",
        "primary": "#e040a0",
        "on-primary-fixed": "#3d0028",
        "surface-bright": "#fef7ff",
        "on-tertiary-fixed": "#001a33",
        "surface-container-highest": "#ece2ec",
        "secondary-fixed": "#eedcff",
        "surface-variant": "#f2e8f2",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#fbf2fb",
        "error-container": "#ffe8e8",
        "outline": "#907898",
        "primary-fixed": "#ffd6ee",
        "on-secondary": "#ffffff",
        "inverse-on-surface": "#fef7ff",
        "tertiary-fixed-dim": "#80d0f0",
        "surface-container": "#f8eef8",
        "on-surface-variant": "#604868",
        "surface-dim": "#e0d6e0",
        "inverse-surface": "#2e1a28",
        "surface": "#fef7ff",
        "on-primary-container": "#2e1a28",
        "on-primary-fixed-variant": "#a02070",
        "secondary-container": "#eedcff",
        "on-surface": "#2e1a28",
        "on-tertiary-fixed-variant": "#005580",
        "on-error-container": "#9b1c1c",
        "error": "#e53e3e",
        "on-tertiary": "#ffffff",
        "surface-tint": "#e040a0",
        "on-secondary-container": "#2e2040"
      },
      borderRadius: {
        "DEFAULT": "1rem",
        "lg": "2rem",
        "xl": "3rem",
        "full": "9999px"
      },
      fontFamily: {
        "headline": ["DM Sans", "sans-serif"],
        "display": ["DM Sans", "sans-serif"],
        "body": ["DM Sans", "sans-serif"],
        "label": ["DM Sans", "sans-serif"]
      }
    },
  },
  plugins: [],
} satisfies Config;
